spring:
  application:
    name: codinviec-gatewayapi
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: codinviec-auth-service
              uri: lb://CODINVIEC-AUTH-SERVICE
              order: 1
              predicates:
                - Path=/api/auth/**, /oauth2/**, /login/oauth2/**

            - id: codinviec
              uri: lb://CODINVIEC
              order: 3
              predicates:
                - Path=/api/**

            - id: codinviec-product-service
              uri: lb://CODINVIEC-PRODUCT-SERVICE
              order: 2
              predicates:
                - Path=/api/product/**
server:
  port: ${SERVER_PORT}


#jwt
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRED} #15m
    refresh: ${JWT_REFRESH_EXPIRED} #7d


#Kiểm tra mapping path
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      enabled: true

#log lỗi
logging:
  level:
    org.springframework.cloud.gateway: TRACE

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
